env = Environment(CPPPATH='src:include')
env.Append(CCFLAGS='-Wall -std=c99 -gstabs+')
env.Program('proto_safe_str', ['src/safe_str.c'])
env.Program('proto_gcc_var_len_arrays', ['src/gcc_var_len_arrays.c'])
env.Program('proto_func_ptr_sample', ['src/func_ptr_sample.c'])

